[package]
name = "hellorust"
version = "0.1.0"
authors = ["Evil Plato"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "~0.8" }
specs = { version = "~0.18" }
specs-derive = "0.4.1"